news_research_task:
  description: >
    conduct thorough research on {topic}
    make sure the research is latest, up-to-date and accurate.
  expected_output: >
    The list of 5 websites with most valuable information of {topic} make sure urls are proper
  agent: news_researcher

news_scraper_task:
  description: >
    scrape news from the list of websites for each website, scraped content should not exceed 100 words and format it in short concise manner in markdown format.
  expected_output: >
    the important information of the scraped content in no more than 100 words
  agent: news_scraper

news_writer_task:
  description: >
    write a news article in markdown format based on the scraped information
  expected_output: >
    full fledged news article with all the important information and section in the markdown format based on the scraped information
  agent: news_writer
